#    Game-in-a-box. Simple First Person Shooter Network Game.
#    Copyright (C) 2012-2013 Richard Maxwell <jodi.the.tigger@gmail.com>
#
#    This file is part of Game-in-a-box
#
#    Game-in-a-box is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>
 
language: cpp
compiler:
  - clang
  - gcc
  
matrix:
  allow_failures:
      - compiler: clang    

install:
# Clang dependencies
 - if [ $CXX = "clang++" ]; then
   sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
   sudo apt-get update -qq;
   sudo apt-get install -qq libstdc++-4.8-dev; 
   fi;
   
# - if [ $CXX = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev clang-3.2; fi

# GCC dependencies
# I'm building with GCC 4.8. Getting that on travis ci is a bit of work.
 - if [ $CXX = "g++" ]; then
   sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
   sudo apt-get update -qq;
   sudo apt-get install -qq gcc-4.8 g++-4.8;
   sudo rm /usr/bin/g++;
   sudo rm /usr/bin/gcc;
   sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++;
   sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc;
   fi;

# libraries needed for everything else.
 - sudo apt-get -q install cmake valgrind libboost-dev libboost-system-dev libboost-thread-dev

script:
  - mkdir build
  - cd build
  - cmake ../
  - make

# RAM: TODO: Make a supression file for all the gmock warnings.
#after_success:
# - valgrind --leak-check=full --show-reachable=yes ./game-in-a-box-common-tests

