#ifdef USING_PRECOMPILED_HEADERS
#ifndef PRECOMPILED_HEADER
#define PRECOMPILED_HEADER
// This file was auto generated by GeneratePrecompiledHeader.sh

#include <vector>
#include <utility>
#include <type_traits>
#include <tuple>
#include <string>
#include <stdexcept>
#include <queue>
#include <memory>
#include <map>
#include <limits>
#include <iterator>
#include <deque>
#include <cstdint>
#include <cstddef>
#include <cmath>
#include <chrono>
#include <boost/asio/ip/udp.hpp>
#include <boost/asio.hpp>
#include <array>
#include <algorithm>

#endif // PRECOMPILED_HEADER
#endif // USING_PRECOMPILED_HEADERS
