#!/bin/sh
echo "#ifdef USING_PRECOMPILED_HEADERS"
echo "#ifndef PRECOMPILED_HEADER"
echo "#define PRECOMPILED_HEADER"
echo "// This file was auto generated by GeneratePrecompiledHeader.sh"
echo "" 
# gets all #includes in all files. Removes DOS line endings and trims whitespace
# Sort, count, sort to count, print.
grep -Rih '^#include <' * | sed -e 's/\x0D$//' | sed -e 's/^ *//g' -e 's/ *$//g' | sort | uniq -i | sort -nr

echo ""
echo "#endif // PRECOMPILED_HEADER"
echo "#endif // USING_PRECOMPILED_HEADERS"
